### ISSUE TITLE
localize the contact email and social media urls

### ISSUE THREAD

**Issue by barrytsai** [oneconcern/oneconcern#13]
in components/layout/BottomBar.vue
<template lang="pug">
footer.footer(:class="{solid: fixed.indexOf($route.name) === -1, white: $route.name === 'careers'}")
 .footer-left(v-html="$store.state.layoutCopy.footerCopyright")

 .footer-right
   a.footer-item.footer-item-contact(href="mailto:contact@oneconcern.com") {{ this.$store.state.layoutCopy.ctaContact }}
   a.footer-item(href="https://www.facebook.com/oneconcern",target="_new")
     span.fa.fa-facebook
   a.footer-item(href="https://twitter.com/oneconcerninc",target="_new")
     span.fa.fa-twitter
   a.footer-item(href="https://www.linkedin.com/company/oneconcern/",target="_new")
     span.fa.fa-linkedin
   a.footer-item(href="https://angel.co/one-concern",target="_new")
     span.fa.fa-angellist
</template>

**Comment by acidjazz** [comment]
![image](https://user-images.githubusercontent.com/967369/53852319-49096c80-3f87-11e9-925a-364383cf1bc7.png)

**Comment by acidjazz** [comment]
```pug
  .footer-right
    a.footer-item.footer-item-contact(:href="copy.footerEmail") {{ this.$store.state.layoutCopy.ctaContact }}
    a.footer-item(:href="copy.footerFacebook",target="_new")
      span.fa.fa-facebook
    a.footer-item(:href="copy.footerTwitter",target="_new")
      span.fa.fa-twitter
    a.footer-item(:href="copy.footerLinkedIn",target="_new")
      span.fa.fa-linkedin
    a.footer-item(:href="coppy.footerAngel",target="_new")
      span.fa.fa-angellist
```
