### ISSUE TITLE
Product page video's

### ISSUE THREAD

**Issue by barrytsai** [oneconcern/oneconcern#14]
https://oneconcern.com/product/

There are currently 3 videos under "Why One Concern is Different".
1) Remove two of them and keep only one of them for JPN website - see the attached screenshot as to which one to keep.
2) Add one new Japanese video: Will provide the new one shortly.
<img width="1316" alt="2-what we do_video" src="https://user-images.githubusercontent.com/10716590/53848249-72ff6680-3f68-11e9-9656-f31640201d36.png">

**Comment by acidjazz** [comment]
Videos are driven by `UserStory` model, if a title is not found, the video will not appear

**Comment by barrytsai** [comment]
Instead of blanking out the title, what do you think about using the "order" field?  If order <= 0, then hide the video.  This way, we won't have to keep track of what the title used to be.

**Comment by barrytsai** [comment]
pages/product.vue:

    for (let entry of userStory.items) {
      if (entry.fields.order <= 0) {
        stories.push({
          quote: entry.fields.quote,
          author: entry.fields.author,
          title: entry.fields.title,
          youtubeId: entry.fields.youtubeId,
          thumbnail: entry.fields.thumbnail.fields.file.url,
        })
      }
    }
