### ISSUE TITLE
The English Quotation mark ("") is showing up on the video

### ISSUE THREAD

**Issue by barrytsai** [oneconcern/oneconcern#49]
<img width="568" alt="Screen Shot 2019-03-19 at 4 06 49 PM" src="https://user-images.githubusercontent.com/10716590/54649882-3142e580-4a69-11e9-9970-b5d041ef092d.png">

**Comment by barrytsai** [comment]
Sorry, we weren't clear.  We would like to remove the double quotes for JP, and keep them for EN.

**Comment by acidjazz** [comment]
@barrytsai would it be best to just put the quotes into the english version instead of hard coding them?

**Comment by acidjazz** [comment]
confirmed working `"` in contentful
